(defun fi-fix (&optional count)
  (interactive)
  (insert "[\"")
  (yank)
  (insert "\", \"")
  (when (null count)
    (setf count 1))
  (dotimes (i count)
    (insert "FI;\\n"))
  (yank)
  (insert "\"],"))