(defun add-load-path (path)
  (add-to-list 'load-path (get-config-path (format "%s/" path))))

(defun enable-site ()
  (add-load-path "site-lisp"))

(defun is-windows ()
  (eq system-type 'windows-nt))

(defun set-font ()
  (set-default-font (if (is-windows)
                        "-outline-Lucida Console-normal-r-normal-normal-16-120-96-96-c-*-iso8859-1"
                      ;; "-outline-DejaVu Sans Mono-normal-normal-normal-mono-16-*-*-*-c-*-iso8859-1"
                      "Lucida Console:pixelsize=14:foundry=b&h:weight=normal:slant=normal:width=semi-condensed:spacing=100:scalable=true")))

(defun fix-scrolling ()
  (require 'smooth-scrolling)
  (let ((line-count 5)) (setq mouse-wheel-scroll-amount `(,line-count ((shift) . ,line-count))))
  (setq mouse-wheel-progressive-speed nil)
  (setq mouse-wheel-follow-mouse 't)
  (setq scroll-step 3))

(defun fundamental-mode-check ()
  (if (equal major-mode 'fundamental-mode)
      (local-set-key (kbd "<tab>") 'tab-to-tab-stop)
    (setq indent-tabs-mode nil)))

(defun setup-cuda-mode ()
  (add-load-path "cuda-mode")
  (require 'cuda-mode)
  (autoload 'cuda-mode "cuda-mode" "Mode for editing CUDA (.cu) source files")
  ;(add-to-list 'auto-mode-alist '("\\.cu$" . cuda-mode))
  (add-to-list 'auto-mode-alist '("\\.cu$" . c++-mode))
  (add-to-list 'auto-mode-alist '("\\.hcu$" . c++-mode)))

(defun miscellaneous ()
  (setq transient-mark-mode t)
  (setq custom-file "~/.emacs-custom.el")
  (load custom-file)
  (setq inhibit-startup-screen t)
  (setq ring-bell-function (lambda ()))
  (setq backup-inhibited t)
  (setq auto-save-default nil)
  (setq buffer-offer-save nil)
  (setq-default indent-tabs-mode t)
  (add-hook 'after-change-major-mode-hook 'fundamental-mode-check)
  (setq kill-whole-line t)
  (delete-selection-mode t)
  (prefer-coding-system 'utf-8)
  (setq default-buffer-file-coding-system 'utf-8-unix)
  (setq column-number-mode t)
  (tool-bar-mode 0)
  (toggle-debug-on-error))